class BaseShareType():
    name =""                   #0
    opening_price = 0.0        #1.today opening price
    last_closing_price = 0.0   #2.yesterday closing prcice
    price = 0.0                #3.current prcice
    max_price = 0.0            #4.today maximum price
    min_price = 0.0            #5.today minimum price
    bid_buy_price = 0.0        #6.is buy 1 price
    bid_sell_price = 0.0       #7. is sell 1 price
    vol_amount = 0             #8 the exchanged share amount, with a unit of 100 shares
    vol_value = 0              #9 the exchanged mount, with a unit of ten thousand yuan
    b1_amount = 0              #10, the amount in 100 shares to be exchanged,
    b1_price = 0.0             #11 the buy one price
    b2_amount = 0              #12
    b2_price = 0.0             #13
    b3_amount = 0              #14
    b3_price = 0.0             #15
    b4_amount = 0              #16
    b4_price = 0.0             #17
    b5_amount = 0              #18,
    b5_price = 0.0             #19
    s1_amount = 0              #20, the amount in 100 shares to be exchanged,
    s1_price = 0.0             #21 the buy one price
    s2_amount = 0              #22
    s2_price = 0.0             #23
    s3_amount = 0              #24
    s3_price = 0.0             #25
    s4_amount = 0              #26
    s4_price = 0.0             #27
    s5_amount = 0              #28,
    s5_price = 0.0             #29
    dates =""                  #30 "2008-01-11",date,
    times = ""                 #31,"15:05:32",time
